//
// Created by xialei07 on 5/19/21.
//

#ifndef HELLOWORLD_MEMBERINITIALIZERLISTDEMO_H
#define HELLOWORLD_MEMBERINITIALIZERLISTDEMO_H


class MemberInitializerListDemo {

};


#endif //HELLOWORLD_MEMBERINITIALIZERLISTDEMO_H
